# https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{.Values.prefix}}-trigger-binding-pr
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitbranch
      value: $(extensions.branch_name)
