apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{.Values.prefix}}-webhook'
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    haproxy-ingress.github.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: '{{.Values.config.ingressClass}}'
    cert-manager.io/cluster-issuer: 'prod-letsencrypt-issuer'
  labels:
    app.kubernetes.io/name: '{{.Values.prefix}}-webhook'
    app.kubernetes.io/component: webhook
    backstage.io/kubernetes-id: '{{.Values.prefix}}'
spec:
  tls:
    - hosts:
        - '{{.Values.config.listenerDomain}}'
      secretName: listener-tekton-tls
  rules:
    - host: '{{.Values.config.listenerDomain}}'
      http:
        paths:
          - path: '/{{.Values.config.name}}/{{.Values.prefix}}'
            pathType: Exact
            backend:
              service:
                name: 'el-{{.Values.prefix}}-event-listener'
                port:
                  number: 8080
