---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
  labels:
    app: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
{{- include "mychart.labels" . | nindent 2 }}
  annotations:
{{- include "mychart.annotations" . | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
{{- include "mychart.labels" . | nindent 6 }}
      annotations:
      {{- include "mychart.annotations" . | nindent 6 }}
    spec:
      {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- include "mychart.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
