---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
  labels:
    app: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
{{- include "mychart.labels" . | nindent 2 }}
  annotations:
{{- include "mychart.annotations" . | nindent 2 }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host . | quote }}
      secretName: "{{- template "mychart.name" . -}}-monofolio-tls"
    {{ with .Values.ingress.additonalHosts }}
    {{- range . }}
    - hosts:
        - {{ . | quote }}
      secretName: "{{- template "mychart.dnsSecretName" . -}}-monofolio-tls"
    {{- end }}
    {{- end }}
  rules:
    - host: {{ tpl .Values.ingress.host . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}-{{- template "mychart.name" . -}}"
                port:
                  number: 8080
    {{ with .Values.ingress.additonalHosts }}
    {{- range . }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Chart.Name }}-{{- template "mychart.name" $ -}}"
                port:
                  number: 5437
    {{- end }}
    {{- end }}